services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - JWT_SECRET=your-super-secret-jwt-key-here
      - SUPERVISOR_USERNAME=administrator
      - SUPERVISOR_PASSWORD=admin123
      - SUPERVISOR_EMAIL=email@mail.com

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
    #change this to server IP >>
      - VITE_API_BASE=http://192.168.1.21:3000
    depends_on:
      - backend